apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultapp
spec:
  selector:
    matchLabels:
      app: vaultapp
  template:
    metadata:
      labels:
        app: vaultapp
    spec:
      containers:
      - name: vaultapp
        image: utibeabasi6/vault-app
        imagePullPolicy: Always
        env:
          - name: VAULT_ADDR
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: vault_addr
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: vault_token
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: vaultapp
spec:
  selector:
    app: vaultapp
  ports:
  - port: 3000
    targetPort: 3000
