apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
data:
  vault_token: cy5velNNWEJCUFY1VXlvbmtiOXBpZzVSb3c=
  vault_addr: aHR0cDovL3ZhdWx0OjgyMDA=
  postgres_password: YWRtaW4=
  postgres_db: dG9kb3M=